Checking finding metadata to see if should block
returntocorp/sgrep-action pull request #37
Opened 2020-08-14 00:40 UTC by brendongo

2020-08-17 17:07 UTC, nbrahms commented
Should this be converted to a PR?

2020-08-18 16:25 UTC, underyx requested changes

2020-08-18 16:25 UTC, underyx commented on src/semgrep_agent/findings.py
> +        return str(self.metadata.get("action", "block")) == "block"
```suggestion
        return str(self.metadata.get("dev.semgrep.actions", "block")) == "block"
```

per https://github.com/returntocorp/semgrep-action/issues/34

2020-08-18 16:25 UTC, underyx commented on src/semgrep_agent/findings.py
> +    metadata = attr.ib(type=Mapping[str, Any], hash=None, eq=False, kw_only=True,)
```suggestion
    metadata = attr.ib(type=Mapping[str, Any], hash=None, eq=False, kw_only=True)
```

Teeny tiny change but might as well 😇

2020-08-18 16:25 UTC, underyx commented on src/semgrep_agent/main.py
>      click.echo(f"=== exiting with {'failing' if exit_code == 1 else 'success'} status")
Could you also print the number of results that were not printed? Something like the sample output in https://github.com/returntocorp/semgrep-action/issues/34#issue-676927729

2020-08-19 20:39 UTC, brendongo commented
IMO much easier to understand what's happening by doing the set operations inline for now rather than having Results/FindingSet expose a bunch of one line functions. Thoughts?

2020-08-20 10:34 UTC, underyx commented
> IMO much easier to understand what's happening by doing the set operations inline for now rather than having Results/FindingSet expose a bunch of one line functions. Thoughts?

Yes, I'm a fan of inline over one-line functions always and forever! 🎉

2020-08-20 10:36 UTC, underyx commented on src/semgrep_agent/findings.py
> +        return str(self.metadata.get("dev.semgrep.actions", "block")) == "block"
```suggestion
        return "block" in self.metadata.get("dev.semgrep.actions", [])
```

I missed this earlier, but the metadata field is an array of actions, so we need to handle it as such

2020-08-20 10:57 UTC, merged