Add --gitlab-secrets-json
returntocorp/sgrep-action pull request #403
Opened 2021-10-15 19:43 UTC by chasemp

Gitlab has moved to a separate scanner type and schema for secret detection.  These results are reported and stored distinct from SAST findings.  The current secret detection schema is reflected at 14.0.0. 

* Note CVE is meaningful in terms of determining unique findings here
* Additional scanner information is included compared to SAST
* Added start and end times for reporting back to gitlab
* Tested on gitlab SaaS offering using generic.secrets.security.detected-aws-access-key-id-value

### Security

- [x] Change has no security implications (otherwise, ping the security team)

2021-10-15 19:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/returntocorp/semgrep-action?pullRequest=403) <br/>All committers have signed the CLA.

2021-10-15 19:43 UTC, chasemp commented
<img width="1005" alt="Screen Shot 2021-10-15 at 2 42 52 PM" src="https://user-images.githubusercontent.com/1850434/137544919-d5606fc9-8750-4057-ada0-6919c69ab686.png">
<img width="985" alt="Screen Shot 2021-10-15 at 2 43 01 PM" src="https://user-images.githubusercontent.com/1850434/137544922-adff0859-1803-4ac9-a2b3-e261393aa707.png">

2021-10-19 21:16 UTC, brendongo requested changes
Can you also add a test like https://github.com/returntocorp/semgrep-action/blob/develop/tests/test_gitlab_output.py intention is to catch any unintended changes if we refactor findings.py or something.

2021-10-19 21:16 UTC, brendongo commented on src/semgrep_agent/findings.py
> +        id_hash = sha224(
Does the syntactic_identifier_int work for this? it's a hash of check_id, path,

2021-10-20 20:01 UTC, chasemp commented on src/semgrep_agent/findings.py
> +        id_hash = sha224(
I think yes, I'm going to do some testing to make sure.  good call.

2021-10-20 20:13 UTC, brendongo commented on src/semgrep_agent/findings.py
> +            "id": str(self.syntactic_identifier_int()),
You might want to use syntactic_identifier_str if it needs to be a string.

```suggestion
            "id": self.syntactic_identifier_str(),
```

2021-10-20 20:37 UTC, chasemp commented
Made this a draft while I revalidate after recent changes.  Cheers and thanks for your help.

2021-10-20 22:02 UTC, chasemp commented
I ran through various test scenarios:

- Same finding same line
- Different findings same line
- Different Findings different line

With treatment (dismiss, et al).  Seems to work a treat.  Good stuff.

2021-10-20 22:03 UTC, chasemp reviewed
test added :)

2021-10-21 21:00 UTC, brendongo commented on tests/test_gitlab_secret_output.py
> +def test_gitlab_secret_output(run_semgrep_agent, get_test_root):
🔥 👍

2021-10-21 21:18 UTC, brendongo approved these changes

2021-10-21 21:19 UTC, merged