Linking to a page for more details
returntocorp/sgrep-action pull request #87
Opened 2020-10-14 21:26 UTC by ievans

2020-10-14 23:44 UTC, ievans commented
@underyx CI failures seem unrelated?

2020-10-22 21:19 UTC, underyx requested changes
Scrutinized this one a bit more than usual since it's hackathon code, hope that's alright.

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
>          for v in sorted(vv, key=lambda v: (v.line, v.column, v.message)):
vvvvv confusing variable names here :D

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
> +    return f"http://localhost:3000/finding/{c.deployment_id}/{v.from_policy_id}?ruleId={v.check_id}&path={v.path}&lineNum={v.line}&rulesetName={v.from_ruleset_id}&projectName={projectName}&policyName
I think the Sapp variable has the actual remote URL as an attribute.

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
> +    return f"http://localhost:3000/finding/{c.deployment_id}/{v.from_policy_id}?ruleId={v.check_id}&path={v.path}&lineNum={v.line}&rulesetName={v.from_ruleset_id}&projectName={projectName}&policyName
Also needs URL encoding; ampersands for instance are probably legal in ruleset names, etc.

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
> +    return next(matches, None) is not None
While it works, `next(iter(...))` is kinda unpythonic. How about

```py
return any(pattern.search(parent.name) for parent in me.parents())
```

?

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
> +    Returns true iff this process is a child process of a process whose name matches pattern
```suggestion
    Returns true iff this process is a child process of a process whose name contains pattern
```

(matches implies `re.match`-like behavior)

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
> +    href: Optional[str],
```suggestion
    href: Optional[str],
    *,
```

I'd force setting the param name for everything below, too easy to mix up the order of boolean flags.

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/meta.py
> +        remotes: List[str] = [remote.url for remote in self.repo.remotes]
```suggestion
        remotes: List[Any] = sorted(self.repo.remotes, key=lambda x: x.remote == "origin")
        return remotes[-1].url if remotes else None
```

1. Other methods return `None` when no answer is available
2. This prioritizes `origin` if available

2020-10-22 21:19 UTC, underyx commented on src/semgrep_agent/formatter.py
> +    projectName = meta.repo_remote_origin
```suggestion
    projectName = meta.repo_name
```

Isn't this the correct name if we want this to identify the configurable project?

2020-10-23 18:11 UTC, ievans commented on src/semgrep_agent/formatter.py
> +    href: Optional[str],
Good idea and willdo (By the way -- this function is copied straight from the old bento code :))

2021-01-27 23:01 UTC, dlukeomalley commented
Closing for now. Thank you for the contribution, and please re-open if this was in error!

2021-01-27 23:01 UTC, closed without merging